### ISSUE TITLE
SquareLine Studio project

### ISSUE THREAD

**Issue by Speedkazze** [fbiego/Lumia-ESP32#8]
Hi,

I tried it and it's really great. Can you upload the SquareLine Studio project, so that it can be adapted and developed further?

I would really appreciate that :)

**Comment by fbiego** [comment]
While some part of the code was originally generated from SquareLine, the projects files are no longer available. Most modifications of the code have also been done outside the scope of SquareLine studio

**Comment by fbiego** [comment]
https://github.com/fbiego/windows-10-mobile-lvgl?tab=readme-ov-file#squareline-studio
